import { guideHref } from '/assets/site-links.js';
export function initHeader(){const b=document.querySelector('#homeMenuButton'),m=document.querySelector('#homeMenu');const close=()=>{m.hidden=true;b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','メニューを開く');};b.onclick=()=>{m.hidden=!m.hidden;b.setAttribute('aria-expanded',String(!m.hidden));b.setAttribute('aria-label',m.hidden?'メニューを開く':'メニューを閉じる');};m.onclick=e=>{if(e.target.closest('a'))close();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.hidden){close();b.focus();}});}
const menus=[['intro','はじめに','入居時のご案内','orange','home'],['equipment','設備','使い方・設定','blue','key'],['section/trash','ゴミ','出し方・収集日','green','trash'],['rules','ルール','暮らしのマナー','pink','rules'],['procedures','手続き','解約・各種申請','purple','procedures'],['trouble','困ったとき','トラブル・連絡先','red','trouble']];
const shapes={home:'<path d="M2 11 12 2l10 9-2 2-2-2v11h-5v-7h-3v7H5V11l-1 2z"/>',key:'<path d="M14 2a8 8 0 0 0-7.5 10.8L1 18.3V23h5v-3h3v-3l2.2-2.2A8 8 0 1 0 14 2Z"/><circle cx="16" cy="7" r="2" fill="white"/>',trash:'<path d="M8 2h8v3h5v2H3V5h5zm-3 7h14l-1 13H6z"/><path d="M10 11v8m4-8v8" stroke="white" stroke-width="1.5"/>',rules:'<path d="M2 4q5-2 9 1v17q-4-3-9-1zm11 1q4-3 9-1v17q-5-2-9 1z"/>',procedures:'<path d="M5 2h11l5 5v15H5z"/><path d="M9 10h8m-8 4h8m-8 4h5" stroke="white" stroke-width="1.5"/>',trouble:'<path d="M10 3q2-3 4 0l10 17q1 3-2 3H2q-3 0-2-3z"/><path d="M12 8v7" stroke="white" stroke-width="2.5" stroke-linecap="round"/><circle cx="12" cy="19" r="1.3" fill="white"/>'};
export function mountHome(main,guide,{element:el,link,icon}){
 const home=el('div','home-screen');
 const modal=(title,build)=>{const d=el('dialog','room-dialog v4-dialog');d.setAttribute('aria-label',title);const c=el('button','room-close','閉じる ×');c.type='button';c.onclick=()=>d.close();d.append(c,el('h2','',title));build(d);d.addEventListener('close',()=>d.remove(),{once:true});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});document.body.append(d);d.showModal();};
 const articles=(title,keys)=>modal(title,d=>{const found=keys.filter(k=>guide.sections[k]);for(const k of found){const a=link(guide.sections[k].label+' ›','#section/'+k,'room-guide-link');a.onclick=()=>d.close();d.append(a);}if(!found.length)d.append(el('p','','この物件のご案内は準備中です。'));});
 const hero=el('section','v4-property');hero.append(el('h1','',guide.title),el('p','','入居後の暮らしをサポートします'));home.append(hero);
 if(guide.roomInfo){const room=el('section','v4-room');room.setAttribute('aria-label','あなたのお部屋');room.append(el('h2','','あなたのお部屋'));const row=el('div','v4-room-heading'),no=el('p','v4-room-number');no.append(el('strong','',guide.room||'お部屋'),el('span','',guide.room?'号室':''));const detail=el('button','v4-detail','詳細を見る ›');detail.type='button';detail.onclick=()=>modal('あなたのお部屋',d=>{if(guide.room)d.append(el('h3','',guide.room+'号室'));let shown=false;for(const [label,value] of [['ポスト開錠番号',guide.roomInfo.mailbox],['宅配ボックス',guide.roomInfo.delivery],['Wi-Fi（SSID）',guide.roomInfo.ssid],['Wi-Fiパスワード',guide.roomInfo.wifiPassword],['駐輪場',guide.roomInfo.bicycle]])if(value){shown=true;d.append(el('p','room-detail-label',label),el('p','room-detail-value',value));}if(!shown)d.append(el('p','','お部屋の詳細情報は登録されていません。'));});row.append(no,detail);room.append(row);const hints=el('div','v4-room-hints');for(const [label,value,symbol] of [['ポスト',guide.roomInfo.mailbox,'rules'],['宅配ボックス',guide.roomInfo.delivery,'box'],['Wi-Fi',guide.roomInfo.ssid,'wifi']])if(value){const item=el('span');item.innerHTML=icon(symbol);item.append(el('span','',label));hints.append(item);}if(hints.childElementCount)room.append(hints);home.append(room);}
 const search=el('label','home-search'),symbol=el('span'),copy=el('span','v4-search-copy');symbol.innerHTML=icon('search');const input=el('input');input.id='homeSearch';input.type='search';input.placeholder='何をお探しですか？';input.setAttribute('aria-label','暮らしの情報を検索');input.setAttribute('aria-controls','homeSearchResults');copy.append(input,el('small','','お湯が出ない、ゴミ、解約など'));search.append(symbol,copy,el('span','v4-chevron','›'));home.append(search);
 const results=el('section','home-results');results.id='homeSearchResults';results.hidden=true;const status=el('p','home-search-status');status.setAttribute('role','status');home.append(status,results);
 const normalize=text=>text.normalize('NFKC').toLowerCase().replace(/[\sー−‐-]/g,'').replace(/ごみ/g,'ゴミ');const aliases={trash:'ごみ ゴミ 分別 収集日',internet:'Wi-Fi wifi ネット 接続',gas:'お湯が出ない 給湯器',heater:'お湯が出ない 給湯器',cancellation:'解約 退去',delivery_box:'宅配BOX 宅配ボックス',key:'鍵 紛失'};
 input.addEventListener('input',()=>{const words=normalize(input.value).trim();results.replaceChildren();results.hidden=!words;status.textContent='';if(!words)return;const hits=Object.entries(guide.sections).filter(([key,s])=>normalize(s.label+' '+s.body+' '+(aliases[key]||'')).includes(words));status.textContent=hits.length?`${hits.length}件の案内が見つかりました`:'該当する案内がありません。別の言葉でお試しください。';hits.forEach(([key,s])=>results.append(link(s.label+' ›','#section/'+key)));});
 const quick=el('nav','quick-menu-grid');quick.setAttribute('aria-label','主要メニュー');for(const [route,title,description,color,symbol] of menus){const a=route==='intro'?el('button','v4-menu '+color):link('','#'+route,'v4-menu '+color);if(route==='intro'){a.type='button';a.onclick=()=>articles('はじめに',['moving','key','electricity','gas','water','internet','special_note']);}const glyph=el('span','v4-icon');glyph.innerHTML=`<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">${shapes[symbol]}</svg>`;a.append(glyph,el('strong','',title),el('small','',description));quick.append(a);}home.append(quick);
 const popular=el('section','popular-info'),heading=el('div','home-section-heading'),h=el('h2'),flame=el('span','v4-flame');flame.innerHTML=icon('heater');h.append(flame,'よく見られる情報');const all=el('button','v4-all','すべて見る ›');all.type='button';all.onclick=()=>articles('すべてのご案内',Object.keys(guide.sections));heading.append(h,all);popular.append(heading);const grid=el('div','popular-grid');for(const [keys,title,photo] of [[['gas','heater'],'お湯が出ない','shower'],[['trash'],'ゴミの出し方','bins'],[['delivery_box'],'宅配ボックス','lockers']]){const k=keys.find(k=>guide.sections[k]),a=photo==='shower'?link('','#no-hot-water','popular-card'):k?link('','#section/'+k,'popular-card'):el('div','popular-card unavailable'),visual=el('span','v4-photo '+photo);visual.setAttribute('aria-hidden','true');a.append(visual,el('strong','',title));if(!k&&photo!=='shower')a.append(el('small','','案内準備中'));grid.append(a);}popular.append(grid);home.append(popular);
 const cta=link('',guideHref('/kurasapo/'),'kurasapo-cta'),phone=el('span','v4-phone'),text=el('span','v4-cta-copy');phone.innerHTML=icon('kurasapo');text.append(el('strong','','くらさぽコネクト'),el('small','','アプリの使い方・できることをご案内します'));cta.append(phone,text,el('span','v4-chevron','›'));home.append(cta);main.append(home);
}
