import assert from 'node:assert/strict';
import { applyPropertyContent } from '../v4/property-content.js';
const source = {delivery_box:{key:'delivery_box',variant:'base',body:'元の本文',label:'宅配ボックス'},gas:{body:'ガス案内'}};
assert.equal(applyPropertyContent('63500',source),source);
assert.equal(applyPropertyContent('11300',{}).delivery_box,undefined);
const fixed={delivery_box:{variant:'kotei_Num',body:'固定番号'}};
assert.equal(applyPropertyContent('11300',fixed),fixed);
const result=applyPropertyContent('11300',source);
assert.equal(result.gas,source.gas);
assert.equal(source.delivery_box.body,'元の本文');
assert.equal(result,source);
const sheetSelected={delivery_box:{variant:'casa_11300',blocks:[{type:'text',content:'シートで編集した本文'}]}};
assert.equal(applyPropertyContent('11300',sheetSelected),sheetSelected);
console.log('PASS: Sheet-selected delivery content passes through unchanged');
const mailboxSource={mailbox:{key:'mailbox',variant:'base',label:'メールボックス',body:'元の郵便案内'},gas:source.gas};
assert.equal(applyPropertyContent('63500',mailboxSource),mailboxSource);
assert.equal(applyPropertyContent('11300',mailboxSource),mailboxSource);
const liveMailbox={...mailboxSource,mailbox:{...mailboxSource.mailbox,variant:'casa_11300',blocks:[{type:'text',content:'シートで編集した本文'}],body:'シートで編集した本文'}};
const mailboxResult=applyPropertyContent('11300',liveMailbox);
assert.equal(mailboxResult.mailbox.label,'メールボックス');
assert.equal(mailboxSource.mailbox.body,'元の郵便案内');
assert.equal(mailboxResult.gas,source.gas);
assert.equal(mailboxResult.mailbox.body,liveMailbox.mailbox.body);
assert.equal(mailboxResult.mailbox.blocks,liveMailbox.mailbox.blocks);
assert.equal(mailboxResult.mailbox.hidePanelTitle,true);
assert.equal(mailboxResult.mailbox.blocks.some(block=>block.type==='image'),false);
console.log('PASS: Casa mailbox only; labels, source, other sections and properties preserved');
